### ISSUE TITLE
the list of files is empty

### ISSUE THREAD

**Issue by mcepl** [mystilleef/eclipse4-fastopen#1]
actually the file `pokus.py` does get open, but I have to type it blindly believing that I won't get the right one.
![empty-list](https://cloud.githubusercontent.com/assets/198999/5506188/ee807c6e-8797-11e4-9f5a-018a9295293a.png)

**Comment by mystilleef** [comment]
Hey, can you test again with the latest version?

**Comment by mcepl** [comment]
With 20150501.0.0 and on  Luna SR2 (4.4.2) `ctrl-r` even doesn’t open the window.

**Comment by mystilleef** [comment]
Can you post your error log?

**Comment by mcepl** [comment]
http://mcepl.fedorapeople.org/tmp/eclipse-error.log

**Comment by mystilleef** [comment]
It looks like the plugin didn't install properly.

# 

!ENTRY com.laboki.eclipse.plugin.fastopen 4 0 2015-05-02 09:51:02.722
!MESSAGE FrameworkEvent ERROR
!STACK 0

# org.osgi.framework.BundleException: Could not resolve module: com.laboki.eclipse.plugin.fastopen [1156]

Try removing the plugin and installing again. You can also launch eclipse with the "-clean" command line argument to remove stale plugin files.

**Comment by mcepl** [comment]
Did both but the result is not much better http://mcepl.fedorapeople.org/tmp/java_error_log_2015-05-05.log ... but it seems there is a more way mess around. I’ll ask our Eclipse developers what’s going on.

**Comment by mystilleef** [comment]
Did you install Eclipse from the Fedora repo or did you install it manually?

**Comment by mcepl** [comment]
It is from the RHEL-7 Software Collection (a development version of that as well), but I guess for all your purposes my `devtoolset-3-eclipse-platform-4.4.2-3.el7.x86_64` is same as `eclipse-platform-4.4.2-5.fc22.x86_64.rpm` from Fedora.

**Comment by mystilleef** [comment]
Yeah, so I tested on a spare laptop using the Eclipse from the Fedora repositories, and it works well for me. But not all plugins work properly. For example, the Code Recommenders plugin doesn't work at all. So I'm sure it might have to do with the Eclipse packaging in the Fedora repositories.

**Comment by mcepl** [comment]
@akurtakov ... any thoughts here?

**Comment by runeflobakk** [comment]
Just wanted to chime in that I also experience this.

It seems to be due to [another plugin](http://sourceforge.net/projects/zipeditor/) that I have installed is throwing an exception:

_Message: Could not create content describer for ZipEditor.gzipfile. Content type has been disabled._

```
java.lang.NoSuchMethodError: org.apache.tools.tar.TarUtils.parseName([BII)Ljava/lang/StringBuffer;
    at zipeditor.model.ZipModel.isTarArchive(ZipModel.java:146)
    at zipeditor.model.ZipModel.detectType(ZipModel.java:120)
    at zipeditor.model.ZipContentDescriber.detectType(ZipContentDescriber.java:47)
    at zipeditor.model.ZipContentDescriber.describe(ZipContentDescriber.java:29)
    at org.eclipse.core.internal.content.ContentType.describe(ContentType.java:161)
    at org.eclipse.core.internal.content.ContentType.internalGetDescriptionFor(ContentType.java:458)
    at org.eclipse.core.internal.content.ContentTypeCatalog.getDescriptionFor(ContentTypeCatalog.java:356)
    at org.eclipse.core.internal.content.ContentTypeCatalog.getDescriptionFor(ContentTypeCatalog.java:360)
    at org.eclipse.core.internal.content.ContentTypeMatcher.getDescriptionFor(ContentTypeMatcher.java:86)
    at org.eclipse.core.internal.resources.ContentDescriptionManager.readDescription(ContentDescriptionManager.java:445)
    at org.eclipse.core.internal.resources.ContentDescriptionManager.getDescriptionFor(ContentDescriptionManager.java:355)
    at org.eclipse.core.internal.resources.File.getContentDescription(File.java:272)
    at com.laboki.eclipse.plugin.fastopen.context.ContentTypeContext.tryToGetContentDescriptionFromFile(ContentTypeContext.java:82)
    at com.laboki.eclipse.plugin.fastopen.context.ContentTypeContext.getContentDescriptionFromFile(ContentTypeContext.java:70)
    at com.laboki.eclipse.plugin.fastopen.context.ContentTypeContext.getContentTypeFromFile(ContentTypeContext.java:62)
    at com.laboki.eclipse.plugin.fastopen.main.EditorContext.getContentType(EditorContext.java:189)
    at com.laboki.eclipse.plugin.fastopen.main.EditorContext.isContentTypeText(EditorContext.java:356)
    at com.laboki.eclipse.plugin.fastopen.main.EditorContext.isTextFile(EditorContext.java:548)
    at com.laboki.eclipse.plugin.fastopen.files.FilesIndexer.isValid(FilesIndexer.java:126)
    at com.laboki.eclipse.plugin.fastopen.files.FilesIndexer.isInvalid(FilesIndexer.java:119)
    at com.laboki.eclipse.plugin.fastopen.files.FilesIndexer.updateFiles(FilesIndexer.java:113)
    at com.laboki.eclipse.plugin.fastopen.files.FilesIndexer.visit(FilesIndexer.java:107)
    at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:126)
    at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:85)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:86)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:86)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:86)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:86)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:86)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:86)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:86)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:86)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:86)
    at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:86)
    at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:120)
    at org.eclipse.core.internal.resources.Resource.accept(Resource.java:95)
    at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
    at org.eclipse.core.internal.resources.Resource.accept(Resource.java:124)
    at org.eclipse.core.internal.resources.Resource.accept(Resource.java:108)
    at com.laboki.eclipse.plugin.fastopen.files.FilesIndexer$1.updateFiles(FilesIndexer.java:78)
    at com.laboki.eclipse.plugin.fastopen.files.FilesIndexer$1.execute(FilesIndexer.java:65)
    at com.laboki.eclipse.plugin.fastopen.task.Task$1.runTask(Task.java:15)
    at com.laboki.eclipse.plugin.fastopen.task.TaskJob.run(TaskJob.java:28)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

Session data:

```
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -keyring /Users/rune/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -keyring /Users/rune/.eclipse_keyring -showlocation
```

I am guessing FastOpen is doing some traversal of files to display, and it involves some interaction with the actual plugins for displaying the files? Maybe it should catch and ignore (and log a warn) if a 3rd party plugin throws an exception, and just proceed to next file?

After I uninstalled the plugin, I see files in the FastOpen-dialog, but they are truncated, and I can't move what looks like another column on top of the files. See screennshot:

![screen shot 2015-05-18 at 12 04 57](https://cloud.githubusercontent.com/assets/174823/7678657/29e177d4-fd56-11e4-9a27-04b70698d652.png)

**Comment by mystilleef** [comment]
@runeflobakk The bug you're experiencing is different from the OP. My my MacBook Pro died so, I'm going to need your help doing some testing. 

https://raw.github.com/mystilleef/eclipse4-fastopen-updatesite/testing/com.laboki.eclipse.updatesite.fastopen

Add this updatesite to your eclipse installation. It should install a testing version of FastOpen. See if this fixes the truncation bug in the screenshot. 

Once that is fixed, we'll work on the other plugin bug.

**Comment by mcepl** [comment]
I have wiped out completely all configuration and I have got just http://mcepl.fedorapeople.org/tmp/eclipse-fastopen-error-log.txt … `[Ctrl-R]`

**Comment by mcepl** [comment]
Oh, I have asked my colleagues to help me and we've got it ... it is simple, the default Java on RHEL-7 is Java 7. Although Java 8 is also available, it is not default. By switching to Java 8 as default, everything works.
